[project]
name = "pytris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abderrahmane Tahri Jouti", email = "tj.abderrahmane@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pytris = "pytris:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
